stages:
  - prepare
  - build

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" && $CI_OPEN_MERGE_REQUESTS
    - if: $CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_REF_PROTECTED == "true"

include:
  - project: univention/dist/docker-services
    file: kaniko.yml
  - local: '/.gitlab-ci/base.yml'

variables:
  pipeline:
    value: ""
    description: "Skip or force jobs: '(skip|force)-(doc|ucslint|build)'"
  BUILD: docker-registry.knut.univention.de/knut/deb-builder

generate-config:
  stage: prepare
  image:
    name: $BUILD
    entrypoint: [""]
  script:
    - .gitlab-ci/build-ci
    - >
      deb-builder
      --yaml .gitlab-ci/base.yml
      --yaml .gitlab-ci/base-deb.yml
      --out generated-config-deb.yml
      --skip src:python-notifier
      */*/debian/control
  artifacts:
    paths:
      - generated-config-doc.yml
      - generated-config-deb.yml

prepare aptly:
  stage: prepare
  interruptible: false
  image:
    name: $BUILD
    entrypoint: [""]
  script:
    - "$CI_PROJECT_DIR/.gitlab-ci/aptly-create || :"
    - $CI_PROJECT_DIR/.gitlab-ci/aptly-publish
  environment:
    name: $CI_COMMIT_REF_NAME
    url: $APT/$CI_COMMIT_REF_SLUG/
    on_stop: drop aptly
    auto_stop_in: 6 month

drop aptly:
  stage: prepare
  interruptible: false
  variables:
    GIT_STRATEGY: none
  image: docker-registry.knut.univention.de/curlimages/curl
  script:
    - "curl --silent --show-error -X DELETE $APTLY/publish/$CI_COMMIT_REF_SLUG/git || :"
    - "curl --silent --show-error -X DELETE $APTLY/repos/$CI_COMMIT_REF_SLUG || :"
  rules:
    - when: manual
      allow_failure: true
  environment:
    name: $CI_COMMIT_REF_NAME
    action: stop

prepare ucslint:
  stage: prepare
  interruptible: false
  extends: .kaniko
  variables:
    KANIKO_BUILD_CONTEXT: packaging/ucslint
    KANIKO_ARGS: --build-arg ucs=$ucs --cache=true
  rules:
    - changes:
      - packaging/ucslint/**/*

doc-pipeline:
  stage: build
  rules:
    - if: "$CI_COMMIT_MESSAGE =~ /skip-doc/ || $pipeline =~ /skip-doc/"
      when: never
    - if: "$CI_COMMIT_MESSAGE =~ /force-doc/ || $pipeline =~ /force-doc/"
    - changes:
      - "doc/[^e]*/**/*"
      - "doc/e[^r]*/**/*"
      - "doc/er[^r]*/**/*"
      - "doc/err[^a]*/**/*"
      - "doc/erra[^t]*/**/*"
      - "doc/errat[^a]*/**/*"
      - "doc/errata?*/**/*"
  needs:
    - job: generate-config
  trigger:
    include:
      - artifact: generated-config-doc.yml
        job: generate-config
    strategy: depend
    forward:
      pipeline_variables: true

deb-pipeline:
  stage: build
  rules:
    - if: "$CI_COMMIT_MESSAGE =~ /skip-build/ || $pipeline =~ /skip-build/"
      when: never
    - if: "$CI_COMMIT_MESSAGE =~ /force-ucslint/ || $pipeline =~ /force-ucslint/"
    - if: "$CI_COMMIT_MESSAGE =~ /force-build/ || $pipeline =~ /force-build/"
    - changes:
      - "[^dt]*/*/**/*"
      - "d[^o]*/*/**/*"
      - "do[^c]*/*/**/*"
      - "doc?*/*/**/*"
      - "t[^e]*/*/**/*"
      - "te[^s]*/*/**/*"
      - "tes[^t]*/*/**/*"
      - "test?*/*/**/*"
      - "test/generate-appliance/**/*"
      - "test/ucs-test/**/*"
      - "test/ucs-test-tools/**/*"
      - "test/univention-demo-configuration/**/*"
  needs:
    - job: generate-config
    - job: prepare aptly
    - job: prepare ucslint
      optional: true
  trigger:
    include:
      - artifact: generated-config-deb.yml
        job: generate-config
    strategy: depend
    forward:
      pipeline_variables: true
