product: ucs
release: "3.1"
scope: ucs_3.1-0-errata3.1-1
src: univention-demo-configuration
fix: 1.0.4-4.13.201305301038
note:
version: [1]
desc: |
  The "univention-demo-configuration" package has been updated in
  order to allow two new UMCP commands. The former package version
  leads to an error message when opening the "App Center" or the
  "Online Updater" UMC module. This issue has been fixed.
bug: [31567]
