include:
  - project: 'univention/documentation/sphinx-docker'
    file: 'pipeline/sphinx.yml'

.sphinx-html:
  extends: .sphinx-html-template
  after_script:
    - !reference [.sphinx-html-template, after_script]
    - 'curl --header "JOB-TOKEN: $CI_JOB_TOKEN" --upload-file "${DOCS_DIR}/${BUILDDIR}/html/objects.inv" "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/${DOC_TARGET_NAME}.${language}/${CI_COMMIT_REF_SLUG}/objects.inv" || :'

.sphinx-pdf:
  extends: .sphinx-pdf-template

.sphinx-linkcheck:
  extends: .sphinx-linkcheck-template

.sphinx-spelling:
  extends: .sphinx-spelling-template

.sphinx-warnings:
  extends: .sphinx-warnings-template

.publish:
  interruptible: false
  variables:
    GIT_STRATEGY: none

review:
  stage: merge
  rules:
    - if: '$CI_COMMIT_BRANCH != $CI_DEFAULT_BRANCH'
  extends: .publish
  tags:
    - omar
  script:
    - 'rsync -av --delete out/ "/var/univention/buildsystem2/test_mirror/ftp/download/docs.$CI_COMMIT_REF_SLUG"'
  environment:
    name: review/$CI_COMMIT_REF_NAME
    url: http://apt.knut.univention.de/download/docs.$CI_COMMIT_REF_SLUG/
    on_stop: stop_review
    auto_stop_in: 1 week

stop_review:
  stage: merge
  variables:
    GIT_STRATEGY: none
  rules:
    - if: '$CI_COMMIT_BRANCH != $CI_DEFAULT_BRANCH'
      when: manual
  needs:
    - review
  allow_failure: true
  extends: .publish
  tags:
    - omar
  script:
    - 'rm -rf "/var/univention/buildsystem2/test_mirror/ftp/download/docs.$CI_COMMIT_REF_SLUG"'
  environment:
    name: review/$CI_COMMIT_REF_NAME
    action: stop

staging:
  stage: merge
  extends: .publish
  tags:
    - omar
  rules:
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
  script:
    - 'rsync -av --delete out/ /var/univention/buildsystem2/test_mirror/ftp/download/docs'
  environment:
    name: staging
    url: http://apt.knut.univention.de/download/docs/
