default:
  artifacts:
    expire_in: 1 day

variables:
  ucs: 446
  GIT_STRATEGY: fetch
  GIT_SUBMODULE_STRATEGY: none
  GIT_DEPTH: "3"
  DOC: docker-registry.knut.univention.de/docbook
  DEB: docker-registry.knut.univention.de/phahn/ucs-devbase:$ucs
  LINT: docker-registry.knut.univention.de/ucslint
  BUILD: docker-registry.knut.univention.de/knut/deb-builder
  LINT_REF: $LINT:$CI_COMMIT_REF_SLUG
  LINT_UCS: $LINT:$ucs
  APTLY: http://omar.knut.univention.de:11620/api
  APT: http://omar.knut.univention.de/build2/git

.docker:
  services:
    - name: docker-registry.knut.univention.de/ucs/docker:dind
      alias: docker
  variables:
    DOCKER_HOST: tcp://docker:2375/
    DOCKER_DRIVER: overlay2
  tags:
    - docker
  image: docker:stable

