product: ucs
release: "5.0"
version: [0]
scope: ucs_5.0-0-errata5.0-0
src: univention-config-registry
fix: 15.0.7-11A~5.0.0.202111021351
desc: |
 This update addresses the following issue:
 * `ucr commit` now prints a warning if a file is specified for which no template is
   registered.
 * `UCR` now immediately closes file references when they are not used
   anymore.
bug: [50010, 53811]
