product: ucs
release: "3.2"
scope: ucs_3.2-0-errata3.2-1
src: univention-config-registry
fix: 9.0.6-9.462.201403131621
version: [1]
desc: |
  This update fixes the following issues:
  * In some cases the file ownership was not preserved correctly when a file is
    committed.
  * The program "univention-check-templates" now also checks UCR template files
    for modifications by using the MD5 hash sum managed by dpkg.
  * If the LDAP server is not available the tool univention-ldapsearch now tries
    to reconnect to the LDAP server. The count can be configured via the UCR
    variable ldap/client/retry/count; the value is set by default to 10.
bug: [34241,24010,34293]
erratum: 72
announced: 2014-03-17
