product: ucs
release: "4.1"
scope: ucs_4.1-0-errata4.1-1
src: univention-config-registry
fix: 11.0.0-3.493.201603231553
version: [0,1]
desc: |
 The following issue has been fixed in univention-config-registry:
 * Service information files in /etc/univention/service.info/services
   are now only considered if they carry the filename suffix ".cfg".
   The behaviour is now similar to the treatment of UCR info files.
bug: [40383]
erratum: 147
announced: 2016-04-13
