product: ucs
release: "4.3"
version: [1]
scope: ucs_4.3-0-errata4.3-1
src: univention-config-registry
fix: 13.0.0-5A~4.3.0.201807161414
desc: |
 This update addresses the following issues:
 * Relax trigger execution to "noawait"
bug: [47356]
erratum: 152
announced: 2018-07-25
