product: ucs
release: "4.3"
version: [2]
scope: ucs_4.3-0
src: docker-compose
fix: 1.8.0-2
desc: |
 This update addresses the following issue:
 * New maintained dependency of Univention App Center.
bug: [43612]
ignore:
  - release+scope.consistent
  - version.scope
erratum: 374
announced: 2018-12-05
