product: ucs
release: "4.4"
version: [1]
scope: ucs_4.4-0-errata4.4-1
src: univention-config-registry
fix: 14.0.0-12A~4.4.0.201909041712
desc: |
 This update addresses the following issue:
 * Fix regression in Erratum 221 which caused the `univention-service` files
   to be not installed any more.
bug: [50098]
erratum: 270
announced: 2019-09-11
