product: ucs
release: "4.4"
version: [0]
scope: ucs_4.2-0
src: configparser
fix: 3.3.0r2-2
desc: |
 This update addresses the following issue:
 * Move to maintained as a dependency of ucslint.
bug: [49588]
maintained: true
ignore:
  - release+scope.consistent
  - version.scope
erratum: 138
announced: 2019-06-05
