product: ucs
release: "4.4"
version: [0]
scope: ucs_4.4-0-errata4.4-0
src: univention-config-registry
fix: 14.0.0-3A~4.4.0.201903141612
desc: |
 This update addresses the following issues:
 * By default univention-ldapsearch appends the argument -o ldif-wrap=no now.
bug: [48683]
erratum: 6
announced: 2019-03-20
