product: ucs
release: "4.4"
version: [1]
scope: ucs_4.4-0-errata4.4-1
src: univention-config-registry
fix: 14.0.0-11A~4.4.0.201908021605
desc: |
 This update addresses the following issue(s):
 * Restarting, Starting and Stopping of various services has been fixed.
bug: [42241]
erratum: 221
announced: 2019-08-07
