product: ucs
release: "4.3"
version: [4]
scope: ucs_4.3-0-errata4.3-4
src: kconfig
fix: 5.28.0-2+deb9u1
desc: |
 This update addresses the following issue:
 * In KDE Frameworks KConfig malicious desktop files and configuration files
   lead to code execution with minimal user interaction. This relates to
   libKF5ConfigCore.so, and the mishandling of .desktop and .directory files.
   (CVE-2019-14744)
bug: [49993]
cve:
- CVE-2019-14744
erratum: 559
announced: 2019-08-14
