product: ucs
release: "4.4"
version: [0]
scope: ucs_4.4-0-errata4.4-0
src: univention-config-registry
fix: 14.0.0-4A~4.4.0.201905212121
desc: |
 This update addresses the following issue:
 * The detection of running services has been enhanced.
bug: [49176]
erratum: 119
announced: 2019-05-29
