product: ucs
release: "4.4"
version: [0]
scope: ucs_4.4-0-errata4.4-0
src: univention-config-registry
fix: 14.0.0-9A~4.4.0.201906171854
desc: |
 This update addresses the following issue:
 * The package now uses dh_python2 instead of python-support for building.
bug: [49129]
erratum: 167
announced: 2019-06-26
